[project]
name = "projeto-uber"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pytest>=8.4.0",
    "selenium>=4.33.0",
    "webdriver-manager>=4.0.2",
]
